apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catalogue-db
spec:
  selector:
    matchLabels:
      app: catalogue-db
  serviceName: catalogue-db
  replicas: 1
  template:
    metadata:
      labels:
        app: catalogue-db
    spec:
      containers:
        - name: catalogue-db
          image: m0ph/catalogue-db:latest
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password_is_empty
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
            - name: MYSQL_DATABASE
              value: socksdb