apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels: 
    app: user-deployment
spec:
  selector:
    matchLabels:
      app: user-deployment
  replicas: 1
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-deployment
    spec:
      containers:
        - name: user
          image: m0ph/user:latest
          ports:
            - containerPort: 80
          securityContext:
            capabilities:
              drop: 
                - all
              add:
                - NET_BIND_SERVICE
          env:
            - name: MONGO_HOST
              value: "user-db:27017"
          resources:
            limits:
              cpu: 300m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi