apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  labels: 
    app: orders-deployment
spec:
  selector:
    matchLabels:
      app: orders-deployment
  replicas: 2
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: orders-deployment
    spec:
      containers:
        - name: orders
          image: m0ph/orders:latest
          ports:
            - containerPort: 80
          securityContext:
            capabilities:
              drop: 
                - all
              add:
                - NET_BIND_SERVICE
          env:
            - name: JAVA_OPTS
              value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
          resources:
            limits:
              cpu: 500m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi