apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels: 
    app: rabbitmq-deployment
spec:
  selector:
    matchLabels:
      app: rabbitmq-deployment
  replicas: 1
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rabbitmq-deployment
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.6.8
          ports:
            - containerPort: 5672
              name: rabbitmq
            - containerPort: 15672
              name: management
          securityContext:
            capabilities:
              drop: 
                - all
              add:
                - CHOWN
                - SETGID
                - SETUID
                - DAC_OVERRIDE
          